[tool.flake8]
ignore = E211, E999, F401, F821, W503
max-doc-length = 72

[tool.black]
line-length = 79
target-version = ['py39']

[tool.isort]
profile = "black"
multi_line_output = 3
py_version = 39